language: rust
rust: stable

jobs:
        include:
                - stage: "Build"
                  name: "Build"
                  script: make
                - stage: "Unit Tests"
                  name: "Unit Tests"
                  script: make tests
